import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { ProductsProvider } from '@/app/Contexts/ProductsContext'
import { CartProvider } from '@/app/Contexts/CartContext'
import Badges from '@/app/components/Badges'
import CartIcon from '@/app/components/CartIcon'
import HomeIcon from '@/app/components/HomeIcon'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartProvider>
          <ProductsProvider>
            <nav>
              <HomeIcon />
              <CartIcon />
              <Badges />
            </nav>
            {children}
          </ProductsProvider>
        </CartProvider>
      </body>
    </html>
  );
}
