import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ProductsProvider } from "@/app/Contexts/ProductsContext";
import Providers from "@/app/providers";
import Layout from "@/app/components/Layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light text-foreground bg-background">
      <body className={inter.className}>
        <Providers>
          <ProductsProvider>
            <Layout children={children} />
          </ProductsProvider>
        </Providers>
      </body>
    </html>
  );
}
