import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/app/providers";
import Layout from "@/app/components/Layout";
import { StrictMode } from "react";

const inter = Inter({ subsets: ["latin"] });

// Update title and description
// Update Favicon
// Add strict mode
export const metadata: Metadata = {
  title: "Burger Galaxy",
  description: "Generated by Max Van Bel",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StrictMode>
      <html lang="en" suppressHydrationWarning>
        <body className={inter.className}>
          <Providers>
            <Layout children={children} />
          </Providers>
        </body>
      </html>
    </StrictMode>
  );
}
